### ISSUE TITLE
BrainGのボス弾　不生成

### ISSUE THREAD

**Issue by Seizya** [FM-Truesa/Touhou-Game#2]
弾が発射される場所に移動しても、スコアが減らないので、ボス弾が生成されてないんだと思います。

**Comment by omasakun** [comment]
解決時には、報告させていただきます。

**Comment by Seizya** [comment]
えぇと、ボス弾生成を ”プレイヤー方式” から  ”エネミー方式” に変更したら持続的に発射されるようになった。だが一番下のみが実行される。(main.jsの460行)原因は”＋＋”による制御なので最大値が実行されるのだと...。
だが、解決方法がわからぬ...。

**Comment by Seizya** [comment]
解決ありがとうです。
